### ISSUE TITLE
Deployment buttons do not work for all platforms everywhere

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#1001]
The following two have issues:

* Heroku a) works from the Readme file in the repo, but does not work from dev.loklak.org
* Deploy to Docker does not work on Readme or on dev.loklak.org

**Comment by AnaghHegde** [comment]
@mariobehling This what i got in the docker documentation.

![screenshot from 2017-02-22 16-17-35](https://cloud.githubusercontent.com/assets/12005551/23208332/9a44a340-f91a-11e6-9787-7f9b504f06b4.png)

And i tried again after logging into docker account and now its working fine. So for the docker i will update the readme.md file. For heroku i am still workin.

**Comment by AnaghHegde** [comment]
@mariobehling 

The basic requirements for creating a button are that your app has a valid app.json file in its root directory, and that the app source code is hosted in a GitHub repository.Heroku Button will not work with repos that have Git submodules. Heroku Button relies on the Build API and uses tarballs fetched from GitHub. GitHub does not include submodule contents when repo-content tarballs are generated.

Since the button is not in the github its not able to find the app.json file. So i think this causing that problem.

The same applies to docker also. Take look at the screenshot below. It says unable to find the stack file. 
![screenshot from 2017-02-22 16-43-07](https://cloud.githubusercontent.com/assets/12005551/23209184/22ce5ec4-f91e-11e6-8a76-de0d11f00a32.png)

**Comment by AnaghHegde** [comment]
@mariobehling Can i open a PR for this?
