### ISSUE TITLE
Do not use Elastic as a database

### ISSUE THREAD

**Issue by yukiisbored** [loklak/loklak_server#1043]
Elastic shouldn't be used as the database for the messages. Elastic is made and meant to be a search engine and it should only keep indexes. We should use another database system to keep the data safely (other than dumps, because dumps aren't used directly, and it should be used as a backup).

We can go for the SQLite route but the main problem is flexibility. There are a couple of non-RDMS solutions that we can use but it has to work without the user setting up the database themself.

I'm not quite sure if ORM can solve the flexibility problem nor if it's a reliable solution.

**Comment by mariobehling** [comment]
@yukiisbored Valid point, but the alternative is not clear as you say.

**Comment by sudheesh001** [comment]
I think elastic is a perfect solution for the scale of data we're looking at. ELK stack has been proven to be scalable and the goto solution to build big data application. SQLite has a terrible performance, If a database change is ever considered I think it should be Postgres because of the SQL/NoSQL support. @Orbiter Your views please ?

I vote for closing this issue and do not favor a change in database.

**Comment by yukiisbored** [comment]
@mariobehling ORM basically helps making objects represented by regular java objects. It may help doing this. but I think @sudheesh001 has a better idea.

**Comment by yukiisbored** [comment]
@sudheesh001 The problem with Postgres is the user have to setup a database first. I think it's better to support the usual MySQL/PostgresSQL while leaving SQLite as the default.

**Comment by Orbiter** [comment]
well that is not an actual requirement because search portals need search engines in the back-end. And thats loklak. You can have fun with a fork of loklak where you may try that.
