### ISSUE TITLE
Markdown stub enhancements 

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_server#106]
This issue is a tracker for all the enhancements that's needed in the markdown servlet.

- [ ] Optimal methods in which the characters are placed across the image, if a long string is present without explicitly mentioning the `\n` characters, the markdown generator generates it as one long line with very small text size as the text gets larger.
- [ ] Currently we can take some size say 80 characters and generate text like these https://twitter.com/sudheesh001/status/628898464517111808 but the text should be wrapped automatically at some whitespace characters.
- [ ] Make the markdown servlet respect `height=<num>&width=<num>` parameters and wrap accordingly.
- [ ] Have a small 2-4px margins on the left and the right so that the text content isn't at the border.

**Comment by Orbiter** [comment]
The biggest problem with your call of the servlet I have right now is: there are no line endings! And between the words where a line ending was is now not even a single space! Please keep the line endings in the call.

**Comment by Orbiter** [comment]
The markdown servlet has been enhanced to handle line endings and required line breaks itself. At this time, not width or height parameter is used because then the client would have to compute the optimum size. This is not easily possible without insights of the rendering process. Therefore the servlet comptes these values on its own.
The margins are there.
