### ISSUE TITLE
No output of video urls of tweets

### ISSUE THREAD

**Issue by vibhcool** [loklak/loklak_server#1171]
tweets having youtube link are considered videos
But the tweet videos are not fetched by TwitterScraper
need to be fixed!!!

Example:-
for url- http://loklak.org/api/search.json?q=video

twitter status:- https://twitter.com/The_Fabled_Fez/status/865186720953905152/

but output doesn't gives video link :-
![screenshot from 2017-05-18 18-18-25](https://cloud.githubusercontent.com/assets/12577433/26202831/59086d58-3bc8-11e7-955f-0dd86e8fb691.png)

**Comment by SKrPl** [comment]
This is because `TwitterScraper` is unable to scrape the video related data. The reason it can't scrape is video/gif related data are displayed to user dynamically (they are not part of the static HTML) and `TwitterScraper` fetches the static HTML data using `ClientConnection` (which uses apache HttpClients). To scrape video/gif related data we need to simulate as if we are doing it using a web-browser (some libraries that can be used Selenium, HtmlUnit).

**Comment by vibhcool** [comment]
yep, we need to do something like http://twittervideodownloader.com/ does, check the link of download button, it fetches twitter video link

**Comment by singhpratyush** [comment]
`youtube-dl` has [an implementation](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/twitter.py) of extracting video URL from Tweets.

We can either reproduce that or use `youtube-dl` itself to extract the URL. The main problem with using it externally is that it will become slow but we will not need to think about maintaining the extractor.

**Comment by singhpratyush** [comment]
Working on it.

**Comment by singhpratyush** [comment]
Shall we use `youtube-dl` binary for this purpose? That way, we will not have to take care of maintaining the scraper, but we may suffer from some performance issue.

Please give your suggestions on this.
