### ISSUE TITLE
Add artwork in svg format for yellow and green icon

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#123]
Currently color icons are in png only: https://github.com/loklak/loklak_server/tree/master/html/artwork

**Comment by sudheesh001** [comment]
Please review and merge https://github.com/loklak/loklak_server/pull/124 which fixes this issue.

**Comment by Orbiter** [comment]
This is a strange fix for a unclear request: I created these images as PNG images and there is no svg source of these colour images. The images had been created using svg files which had been transformed to png to make it possible to fill them with colour. I admit that this process could be done more professionally, but however I am developer, not designer.

Sudheesh made a solution which I did not understand, because there are no sources for svg images but the png. Transforming png to svg does not create any advantage over the original png. However, svg are available now and may be exchanged with 'real/source' svg images sometime, anytime.

**Comment by Orbiter** [comment]
I just updated the svg graphics which should now contain the vector graphics
