### ISSUE TITLE
Loklak.org restricting dump download size approx. to 1.08GB and disconnects client

### ISSUE THREAD

**Issue by paraabeli** [loklak/loklak_server#125]
Hi,
just wanted to notify that loklak.org disconnects file transfer when it reaches approx 1.08GB
Two example download samples after disconnect:
1,081,819,136 bytes
and
1,081,147,392 bytes

Seems that server side disconnects when reaching near those values. Ive tested this with 2 different isp's connections and with my own computer + server (tried with curl,wget,chrome,firefox and IE).

I got proposal for this project about dump distribution:
Torrent module for global distribution for dumps and api for calling dump downloading from global dump index.

So, what i mean with this is that every loklak server could offer their dumps to global torrent listing if they want and other loklak istances could choose what dumps they might want to download themselves for filling index. This could be very good for harvesting older dumps to fill up historical tweets. 

Also torrent approach would reduce bigger(older) loklak nodes bandwidth usage when there are multiple seeders after initial dump downloads. This could offer also chance for those who want to backup global dump index and support preserving older dumps if loklak nodes or node stops running by their operator.

Br,
Paraabeli

**Comment by smokingwheels** [comment]
@paraabeli 
Just my 2 cents worth..
Historical tweets are fine.
I would prefer fresh and upto date information to look at. A tweet impression has a short life span usually which http://loklak.net keeps track of in Twitter if you sign up.

**Comment by smokingwheels** [comment]
If you Want you can use recover the gz file it seems to be truncated though.

**Comment by smokingwheels** [comment]
The download still truncates I used Iceweasel, Chrome and Wget.
This maybe a solution to split the files. 

https://www.linux.com/community/blogs/133-general-linux/20994

One time, when we want to uploading a file, we are having difficulties because the file size is too large and our internet speed is so slow. Therefore, we must split our file into some small parts so we can upload it per small parts. How to do this?

 First, we must compress the file with tarball archiver.

$ tar -cvvzf <archive-name>.tar.gz /path/to/folder

This command file archive our folder to *.tar.gz. We can use file instead of path to folder for the argument. Then we will split up our file archive into small parts.

$ split -b 1M <archive-name>.tar.gz "parts-prefix"

-b 1M will split the file into 1 Megabytes size of file.The "part-prefix" will give the prefix name of our parts of file.

Example:

We have a video file name video.avi that have size of 30 MB. We will split it into 5 MB per parts. We can do :

$ tar -cvvzf test.tar.gz  video.avi

$ split -v 5M test.tar.gz vid

This command will create the archive file name test.tar.gz. Then, it will split into (approximately) six parts of 5MB file. They have prefix "vid", so the result will be vidaa, vidab, vidac, vidad, vidae, and vidaf. We can use number instead of letter on the suffix by adding -d option on the split command

$ split -v 5M -d test.tar.gz video.avi

 to join this file, we can use cat command.

$ cat vid* > test.tar.gz

**Comment by Orbiter** [comment]
I like the torrent approach. I don't know if there are java libraries which make automatic seeding easy. Any ideas?

**Comment by smokingwheels** [comment]
I found this one not too sure if it does what you want.
https://github.com/mpetazzoni/ttorrent
I will keep looking.

**Comment by smokingwheels** [comment]
@Orbiter Is it possible that the compression of the message file is done with it open?
Thus giving unexpected end of archive when decompressing.
I have the 4 files in question and they range from 5.5 to 6.1 GB uncompressed after running a tar recovery on them in Linux.
Does this match the uncompressed size on loklak.org ?

I have been expermenting today and most times my program won't end when downloading the uncompressed message data in small amounts. I am also overwriting the contents of the message file back to nothing, not sure if this is the cause though.

**Comment by smokingwheels** [comment]
@paraabeli @Orbiter 
I manually put a 11 gb txt file on the root web server directory and was able to download all of it on the LAN.  I will import the messages and try again.

**Comment by Orbiter** [comment]
woah! is this full with tweets or is is just a dummy test file?

**Comment by smokingwheels** [comment]
It is full of tweets 2 of the recovered files from loklak.org.
I do have close to 100 million tweets which 49 million are from loklak I should process them one day with an import its 80 Gig Raw.

The link smokingwheels.mooo.com:9000/message.txt is where its stored on the server you have to use wget command because there is no link as yet. if you click on it in a browser it will have a stressful time.

It may take over 40 hours to download but you should be able to tell after 4 hours.

**Comment by Orbiter** [comment]
I believe I found the source of the problem and solved it:
- I was unable to find a cause in the loklak code. Tests with local instances always succeeded.
- I considered a timeout, but did not found a cause for that
- after more debugging code an idle timeout after 20 seconds idle time gave a hint: idle timeouts can only happen if the client is not trying to download - which is not the case. The only cause could be 'something in the middle'
- there is actually something between loklak and the client on loklak.org: a nginx for fail-over operation mode. nginx in reverse proxy mode has actually a 1GB limitation by default
- http://www.nginxtips.com/optimizing-nginx-for-serving-files-bigger-than-1gb/ and http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_max_temp_file_size pointed to the solution
- now increased the temp file size in nginx to 24GB, that is the new limit.

**Comment by smokingwheels** [comment]
Ok Cool I will give it a try
