### ISSUE TITLE
When does data (tweets, users) get saved and deleted

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#126]
We had a much higher number of data items saved formerly currently it is only 18.442693 tweets for example. What is the reason? How can we maximize the data storage?

**Comment by Orbiter** [comment]
We had a crash of the index when I tried to add another second loklak_server for redundancy. I had to delete the elasticsearch index and I am filling in the dump of the tweets step-by-step. This process is ongoing and I did this many times in the past which was probably unnotices because the dump was smaller.
