### ISSUE TITLE
api.loklak.org  showing 502 bad gateway

### ISSUE THREAD

**Issue by aayusharora** [loklak/loklak_server#1287]
## Steps to Reproduce
1. Make a query to `https://loklak.org/api/search.json?timezoneOffset=-330&q=` + query parameter
2. The response shows **Bad Gateway**.

**Comment by singhpratyush** [comment]
@aayusharora: This happens when we the server is updating (or other minor issue) and the `502` vanishes in some time. Please ping us at https://gitter.im/loklak/loklak if the error stays for long time.

**Comment by sudheesh001** [comment]
This is a application downtime issue which happens when the prod servers are updating or being rebuilt. The nginx throws a 502 since theres no application to capture the request as indicated. This is good to close. We should slowly figure out how we can update these servers without causing these downtimes.
