### ISSUE TITLE
when scraping HTTPS, can you save full authenticated TLS session?

### ISSUE THREAD

**Issue by gojomo** [loklak/loklak_server#131]
Just wondering: when you scrape tweets, by any chance do you save the entire TLS session (including any ephemeral client-side key-matter)? 

I ask because if you did, the full session could serve as authentication that Twitter's secure servers themselves provided the content. (In a world of tampered-DOMs and screenshots, and re-shared captures from potentially mischievous peers, that'd be useful for a trustworthy tweet-archive.)

**Comment by smokingwheels** [comment]
First impression interesing.

If you study the Data harvested so far to date there are lots of tweet robots or scheduled tweeters/retweeters.
Twitter does ban some of them in time. The way to tell is to send a tweet out to some of them. In my last effort not 1 reply in 1000's of tweets but approx 20% dead accounts, but the data is over 6 months old now.

If Loklak as is had an unrestricted search allowance on Twitter scraping you might be able to go thru the people you are following and weed out the source to the "mischievous peers" in some endless loop arrangment.

I have noticed on my Twitter feed that quite a few have stopped tweeting since I ran my last experment. 
Also I have had my impressions looked at and lost approx 20%.

**Comment by Orbiter** [comment]
well if this is possible, it is still a lot of work to make a full infrastructure for this (how often should the TLS session be checked and what should be done if this fails).
Please go for a solution that you implement yourself, otherwise this will go into the backlog of never-implemented enhancement requests.

**Comment by mariobehling** [comment]
@gojomo Cool idea! But, as mentioned we cannot take on this task as we don't have the necessary resources. I am closing this issue therefore.
