### ISSUE TITLE
WearCityHack Berlin: FAQ

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#135]
Please post any questions you have during the #wearcityhack (http://wearcityhack.com) Berlin here.

**Comment by mariobehling** [comment]
Do we have command line parameters to force the server in interactive mode?

**Comment by Orbiter** [comment]
I don't know what 'interactive mode' means. However, there a re no command line parameters.

**Comment by sudheesh001** [comment]
@mariobehling The command line parameters is an attempt I am making in the `python-loklak-api` The barebone is here, but it needs more work. 
https://github.com/loklak/python-loklak-api/blob/master/loklak.py#L212-L223

**Comment by Orbiter** [comment]
due to your activities at the hackathon there are obviously a large number of harvesters running now! :sweat_smile: 
:cyclone: :cyclone: :cyclone:

This caused a 'tiny' problem: the loklak.org server run out of query suggestions. New peers just don't have luck getting search requests for harvesting. To work around this problem, I added https://github.com/loklak/loklak_server/commit/6522cc55fecce6ce62010c3e2cd41eb77247ddb2 to the harvester to get more query words based on the context of the current message timeline. Please update your peers!

**Comment by Orbiter** [comment]
event finished
