### ISSUE TITLE
not-localhost is not allowed by Access-Control-Allow-Origin.

### ISSUE THREAD

**Issue by sevazhidkov** [loklak/loklak_server#166]
Hi!
I'm creating a heat map with tweets using Loklak API - http://sevazhidkov.github.io/tweet-heatmap/
I have created cloud instance of Loklak API using Docker, IBM Bluemix and this tutorial: https://titanpad.com/loklak-bm
When I'm trying to call API from site on Github Pages (http://sevazhidkov.github.io/tweet-heatmap/), I'm getting this error:
```
XMLHttpRequest cannot load https://loklakgci.mybluemix.net/api/search.json?q=Fossasia. Origin http://sevazhidkov.github.io is not allowed by Access-Control-Allow-Origin.
```
When server in localhost, everything ok. How I can give access to Loklak API from external site?

**Comment by sudheesh001** [comment]
How about configuring this line 
https://github.com/loklak/loklak_server/blob/53aa5b71dac24b8faf6716e76600943e4bd90792/conf/config.properties#L75

Feel free to close this if it's worked.

**Comment by niccokunzmann** [comment]
This is the request sent with Firefox:

    https://loklakgci.mybluemix.net/api/search.json?q=asasasasasasasasasasa

    GET /api/search.json?q=asasasasasasasasasasa HTTP/1.1
    Host: loklakgci.mybluemix.net
    User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0
    Accept: application/json, text/plain, */*
    Accept-Language: en-US,en;q=0.5
    Accept-Encoding: gzip, deflate
    DNT: 1
    Referer: http://sevazhidkov.github.io/tweet-heatmap/
    Origin: http://sevazhidkov.github.io
    Connection: keep-alive

    HTTP/1.1 200 OK
    X-Backside-Transport: OK OK
    Connection: Keep-Alive
    Transfer-Encoding: chunked
    Content-Type: application/json; charset=UTF-8
    Date: Sat, 26 Dec 2015 11:09:50 GMT
    Expires: Sat, 26 Dec 2015 11:09:52 GMT
    Last-Modified: Sat, 26 Dec 2015 11:09:50 GMT
    Server: Jetty(9.2.6.v20141205)
    X-Cf-Requestid: 6c11239a-6e32-4b19-5c3e-e6a466645d20
    x-robots-tag: noindex,noarchive,nofollow,nosnippet
    X-Client-IP: 87.78.140.197
    X-Global-Transaction-ID: 2711700983
    ----------------------------------------------------------

I seems like the LokLak server should send some "allowance" so that the request is granted by the browser, according to  something like https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

    Access-Control-Allow-Origin: *

should be sent as response.

**Comment by sudheesh001** [comment]
Yes @niccokunzmann You're right, By default CORS is disabled but it can be allowed by configuring the settings. :smile:

**Comment by sevazhidkov** [comment]
But loklak.net connecting to loklak.org and it's working. Is there a whitelist with approved sites?

**Comment by YagoGG** [comment]
Same here.
@sudheesh001, neither with `elasticsearch.http.cors.enabled` set to `true` nor `false`.
I'm directly running it from `localhost`. Any other ideas?

**Comment by sevazhidkov** [comment]
@sudheesh001, I set it too, but it's still not working with same error. 
My ```data/settings/customized_config.properties```:
```
# This file can be used to customize the configuration file conf/config.properties

elasticsearch.http.cors.enabled=true
elasticsearch.http.cors.allow-origin="*"
```

**Comment by sudheesh001** [comment]
Did you try the request using `jsonp` like how its done in loklak_webclient, Would that work ?

**Comment by YagoGG** [comment]
@sudheesh001 `JSONP` definitely works, and it's OK for developing and testing, but it shouldn't be used as the production method for gathering the data from loklak.

**Comment by Orbiter** [comment]
@sudheesh001 jsonp is enabled almost everywhere in the loklak api at port 9000 but nowhere in the elasticsearch api at port 9200 - on purpose. That would be a security leak
@YagoGG there is no reason to say in generat that jsonp should not be used in production. We use jsonp in the loklak api for production on purpose. There is no use to discuss this for the elasticsearch api at port 9200 because jsonp is just not there
@sevazhidkov I had problems with the cors setting of elasticsearch as well, but solved it recently with this commit: https://github.com/loklak/loklak_server/commit/a335d2f6744df56c6c6012b617d63229a84a47ce --that still means that the request only works from localhost. If we want to use a elasticsearch port 9200 for public pages, I recommend to proxy that through a (not yet existent) loklak api. But that elasticsearch.http.cors.allow-origin setting is good enough for local testing.

**Comment by YagoGG** [comment]
@Orbiter, as far as I know, JSONP isn't safe to use mainly because it's a *hack* to bypass a browser's protection. JSONP has the risk it allows a third party service (in this case, loklak) to run code in the client's website.  
Obviously, loklak has good intentions and won't intentionally make [CSRF](https://en.wikipedia.org/wiki/Cross-site_request_forgery) attacks. But if the public loklak server instance (or whichever the user uses) gets compromised, malicious code could be run in many applications.  
[Here](http://security.stackexchange.com/a/23439) are more details for not using JSONP, from the safety's perspective.
In my opinion, if it's possible to enable `Access-Control-Allow-Origin` headers for the whole API, that'd be great. It would allow connecting through XMLHttpRequest, which seems safer to me.

*P.S.: I'm not an expert in the matter, so it's quite probable I'm wrong about all of this. Feel free to make as many corrections as you see necessary ;)*

**Comment by sevazhidkov** [comment]
If I use JSONP, I'm getting this error:
![2016-01-09 18 47 42](https://cloud.githubusercontent.com/assets/6896447/12216617/98d5de72-b701-11e5-9fc5-8447d209d25b.png)
How can I fix it?

**Comment by YagoGG** [comment]
@sevazhidkov Would you mind posting your code?

If you're interested, you can also take a look at [this](https://github.com/YagoGG/loklak-fetcher-client) JavaScript library I made, that uses JSONP to get loklak's API tweets. Maybe that can help you solve your issue.

**Comment by sevazhidkov** [comment]
It's open source - https://github.com/sevazhidkov/tweet-heatmap

**Comment by YagoGG** [comment]
[Here](https://github.com/sevazhidkov/tweet-heatmap/blob/gh-pages/js/tweet-heatmap.js#L34) you should specify the callback function. In your case, because you're using jQuery, it's `JSON_CALLBACK`:

```javascript
$http.jsonp('http://loklak.org/api/search.json?callback=JSON_CALLBACK&q=' + $scope.query).
```

**Comment by sevazhidkov** [comment]
I'm using Angular.js, but your advice helped. Thank you very much, it was really helpful.

**Comment by YagoGG** [comment]
Ooooops! Not quite familiar with any of them :S

**Comment by Orbiter** [comment]
@sevazhidkov IT WORKS! wow, I like it!

**Comment by sevazhidkov** [comment]
Thank you! Sent it to review.

2016-01-09 20:06 GMT+04:00 Michael Peter Christen <notifications@github.com>
:
