### ISSUE TITLE
Home page Load time can be 30% faster if images are reduced in color depth  

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#17]
Struggling on ADSL 2+ here is a slight performance increase if you need it.
My Debian VM host is 43% slower to load if all is left alone.

Results 
Before http://www.webpagetest.org/result/150427_90_7BE/
After http://www.webpagetest.org/result/150427_0X_7K4/

I converted the following files to 256 color resolution.
loklak_anonymous.png
loklak_share.png 
loklak_collect.png
It does put a white box and not match the home page color the cow also changes a little.
![loklak_anonymous](https://cloud.githubusercontent.com/assets/11748913/7341989/f1d99f56-ecde-11e4-986b-7e57ef0be8b6.png)
![loklak_collect](https://cloud.githubusercontent.com/assets/11748913/7341990/f1ddb758-ecde-11e4-8a56-26ac3d822725.png)
![loklak_share](https://cloud.githubusercontent.com/assets/11748913/7341991/f1e0547c-ecde-11e4-884a-37c607975762.png)

**Comment by sudheesh001** [comment]
@smokingwheels I think having an alpha background image is better than having images which do not blend in with the background, though this has a lighter footprint, I think its a bad move to replace the images there.

Maybe we could try looking at the [optipng](http://linux.die.net/man/1/optipng) tool to compress the images to a minimum size so that they can be used.
@Orbiter What do you think about this ?

**Comment by Low012** [comment]
I have managed to get pretty good results by using [pngquant](https://pngquant.org/) first and then running optipng. Or just use [TinyPNG](https://tinypng.com/) if the number of images is small and their content is not confidential.

**Comment by smokingwheels** [comment]
Ok thanks @Low012 I am quite happy with the results from TinyPNG.
