### ISSUE TITLE
Inconsistency between crawling rate and actual growing rate.

### ISSUE THREAD

**Issue by DengYiping** [loklak/loklak_server#190]
Loklak has a feature to show crawling rate. However, the daily rate seems far-fetch from the actual rate. Example: [my_server](http://geekinguniverse.com:81) My server has beat the daily rate multiple times in couple hours.

**Comment by Orbiter** [comment]
Yes I admit that the count method is confusing and maybe not what you expect: it is counted how many tweets have been stored for the time span of one day - the last 24 hours. Because collected tweets are also from the past before those 24 hours, the computed growth rate (messages per day) is lower than the collection rate.

Recently also the last 10 minutes are measured and upscaled to 24 hours and the number presented is the maximum of both.

The reason why this is computed this way is, that it is easy: the search index gives this result using a simple count. Counting the actual growth rate would either require to add a date field (collected_time) to the search index or it would require to store collection marks as seperate data structure.

Do you have a suggestion how to compute the result which you expect?

**Comment by DengYiping** [comment]
Maybe we can create a thread and keep track both the insertion of elastic search (push, harvesting) and the time, and calculate the rate gradually.

**Comment by Orbiter** [comment]
yeah, maybe not a thread but just a map with this information. It could be filled in the Caretaker process. But there is still a problem: It would count the number of harvested tweets, but it would not give you the number of tweets that are created _for_ one day but harvested _in_ one day. We would need to display two numbers. Would that not be confusing?

**Comment by mariobehling** [comment]
Well, why don't we just show "x" tweets collected in the last 24 hours and "y" tweets per hour?

**Comment by Orbiter** [comment]
That still does not distinguish _in_ and _for_. Maybe naturally everyone would understand that such numbers are always _in_ but we currently present _for_.

**Comment by mariobehling** [comment]
We could always have a detailed page with more numbers and all kinds of cool statistics "more stats". Here you could add "projected collection rate for the next 24 hours". I understand that on the main page the goal is to attract people with a nice number. The "number of collected in the last 24 hours" is higher and therefore more impressive. So, I would go for this.

**Comment by Orbiter** [comment]
Yes thats true. So building a index size track to compute this comes to the work heap.

**Comment by smokingwheels** [comment]
What about adding a totalizator figure to each gz dump file when done being compressed and then add them all up and have a total number on the front page for Messages and Users?
I like it the way it is. If you want more details download the message file on another system and process the raw data with the time stamps eg {"created_at":"2015-05-01T20:14:00.000Z" per message.

Just a very rough guess on the current loklak server dump holds 270 million tweets in the dump files.
The calculation is based on 81 GB for 100 million tweets, I have checked this in june last year.
There is 39 GB of Compressed data now when extracted would roughly be 218 GB.
[Loklak Splitter](https://github.com/smokingwheels/loklak_split) is a QB64 Program to cut up the Dump files. 
QB64 install guide on Debian  [QB64 install](http://smokingwheels.mooo.com/forum/topic.asp?TOPIC_ID=93)

**Comment by Orbiter** [comment]
I will implement this using the elasticsearch _timestamp method, see https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-timestamp-field.html
Then we will be able to evaluate this with kibana as well.

**Comment by DengYiping** [comment]
Looks good, thank you!

**Comment by Orbiter** [comment]
implemented since some weeks. The trigger to load the new field was added in https://github.com/loklak/loklak_server/commit/8fc0675fb82c16d3318a92068ecea2816adb6882
