### ISSUE TITLE
send emails from the server

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#361]
this is required for password recovery: a class that provides a method to send out an email.
required attributes are:
- address:to
- address:from
- subject
- text
Create this simple class first and evaluate what is needed to attach this to a mail server (if any).
We will connect that to password recovery later.

**Comment by shivenmian** [comment]
@Orbiter I am almost done with the stub. Should I add the password recovery option in that sign-up page?

**Comment by Orbiter** [comment]
oh great! I believe the password recover option should be on a log-in page. We don't have that yet.

**Comment by shivenmian** [comment]
Yeah, I'm making the Sign Up page but I intend on keeping the UI same for the login. I could make the login page too with just some adjustments, so asked. Thanks. I'll submit the signup app in a bit.

**Comment by shivenmian** [comment]
Also @Orbiter the authentication stuff will be done a bit later right?

Because even apart from the hashing etc, we can have basic authentication too, i.e password and confirm password field is same, password should have atleast 'x' letters and have special chars, email ID is of a valid form etc. I've just made a static webpage as of now.

Do you want me to add this ^ now, or will we add all the authentication later?

**Comment by Orbiter** [comment]
very good, just submit it as a stub (just add 'stub' to the commit message text, so it's clear its unfinished)

**Comment by shivenmian** [comment]
Stub completed, rest milestones in #467.
