### ISSUE TITLE
create basic peer information and create a peer hash

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#377]
right after the public key is created, check if there is a DAO.public_settings.peer_hash attribute.
If not existent, create it with this formula:
DAO.public_settings.peer_hash = base64(DAO.public_settings.public_key.hash())

This will make it possible that we can send a challenge to a peer to decrypt something we send them using the public key of that peer to encrypt something. Since the hash comes from the public key, only the creator of the key pair can be the owner of that hash. That makes it impossible to make a fraud hash.

It is important that a peer hash is only created when a key pair is created.

**Comment by Orbiter** [comment]
this requires https://github.com/loklak/loklak_server/issues/375 first

**Comment by treba123** [comment]
The standard hash function is not secure. I implemented it via sha256.
Also, direct acces to the values is not so cool in this case, so I created get/set function to take care of everything

**Comment by treba123** [comment]
Hej @Orbiter regarding the hash thing: what you were refering to was [collision resistance](https://en.wikipedia.org/wiki/Collision_resistance) if i get you right.
So we want that it's extremly hard for an attacker to be able to create a key with the same hash as some other.
That's why we really shouldn't use anything weaker than sha256 for creating the hash, I'd actually prefer to use something like [bcrypt](https://en.wikipedia.org/wiki/Bcrypt) but didn't yet pull in any big library for it as sha256 is still regarded as pretty save.

If I get you right, you wanted to put constrains on the hash, like having so and so many zeros at the beginning. That's probably very unsecure, as it makes the room our hashes exist in smaller, making it actually easier to attack it (or did you want to make constrains on the key? anyway, both is actually dangerous)

**Comment by treba123** [comment]
see above
