### ISSUE TITLE
Read the peers.json and convert it into a CSV file as required for forming FDG.

### ISSUE THREAD

**Issue by daminisatya** [loklak/loklak_server#462]

**Comment by daminisatya** [comment]
As of now the graph is reading the test json file which contains the peers.json object. We need to convert the .json file into CSV file and add the other required fields.

**Comment by sudheesh001** [comment]
@daminisatya Is there a specific format you're looking for do you want all the fields in the current json to be in the csv ?

**Comment by Orbiter** [comment]
why would you need a csv file, which software does that need?

**Comment by sudheesh001** [comment]
@Orbiter To visualize the graph with d3, it's easiest to show a parent-child relationship with a csv as `d3.csv()` is built in and reads row by row making it easier, `d3.json()` too does the job but gets messy. I think the required format would be
`source(loklak.org),target(host),port.http,port.https,lastSeen,lastPath,PeerName`
Since this is only for the visualization to work, I think we can add `/peers.json?format=csv`

**Comment by Orbiter** [comment]
Please implement ```peers.csv```. This can be done with the same servlet class. Please see https://github.com/loklak/loklak_server/blob/master/src/org/loklak/LoklakServer.java#L505-L507 and https://github.com/loklak/loklak_server/blob/master/src/org/loklak/LoklakServer.java#L525-L527 as example how the same servlet can return different contents.

**Comment by sudheesh001** [comment]
Self assigning.
