### ISSUE TITLE
Anonymized data

### ISSUE THREAD

**Issue by treba123** [loklak/loklak_server#555]
This is just an idea about the general future of the project, concerning how we handle data on the long run.

As one major goal of loklak is to collect and connect massiv amounts of data and make it usable for science and good(tm) projects, we should think about how to handle all this responcively.
In the scientific community this has long been a discussion, as for many usecases, researchers are not really interested in identifiable personal information.
At the same time, data can be misused, for example by oppressive regimes or criminals.

The general question is, how to make information usable without bringing individuals in danger.

Here's a little read up about early steps in this direction for everyone interested. Of course, there's much further developed concepts about this today

https://epic.org/privacy/reidentification/Sweeney_Article.pdf

So in the end, we're developing free software and the data we collect from social networks is available anyways. 
Still for loklak as an organization which control many servers and has a massiv database that it plans to offer, it's maybe worthwhile to atleast try to bring up a little bit of protection.

This could also be an very interesting **feature for universities**, as many research projects have to go through an **ethics board** (most publishers of scientific papers demand this)
They might not be allowed to use loklak data in an unanonymised way, making this a selling point.

**Comment by mariobehling** [comment]
@treba123 Thanks for bringing this up. This is a very important huge subject, but I am afraid we cannot solve this issue here and our issue tracker is not the right place to discuss this. There is no good answer to this question. It addresses an old dilemma - should you do something even though it could potentially be used in a bad way? Also, to be realistic as a matter of fact loklak is not really an organization that controls a big infrastructure and this topic should be rather discussed more globally - addressing the real data collectors of the world. For a long time we will not be matching them (maybe never). 

Currently the big question is, how we can we make our infrastructure run and what are useful features to evaluate the data we are collecting. Discussions about what data could be analyzed and how to make it anonymous result in all kinds of outcome up to the point where people will say, let's not collect data at all. loklak right now only collects public data. So this data is already out there. 

Discussions about implications of data richness and anonymity are important, but here in this tracker we are focusing on code, bugs and feature requests. It would be great, if you make a session about anonymous data at the next OpenTechSummit or at the CCC. If there are specific feature requests about supporting anonymity features in loklak we can add the issues in the tracker.

**Comment by treba123** [comment]
@mariobehling would love to do that. I'm currently even considering making this topic part of my bachlor theses which I'll start after the GSoC. Maybe that could go into Loklak

**Comment by mariobehling** [comment]
:+1:
