### ISSUE TITLE
Impact of services integration on data schema

### ISSUE THREAD

**Issue by zyzo** [loklak/loklak_server#60]
Right now the data saved and searchable via `search.json` have more or less the same schema as twitter's data. When integrating other services, the data isn't always tweet-like, or each data entity might  be other things than a message attached to a user. 

For example, when I search for FOSSASIA API data, I get some fields that I never used, and there are some custom fields that I want to add as well. So using `MessageEntry` schema to save api data might not be the best idea. 

I can only think of two ways to solve this problem : 
* allow saving and searching for raw jsons
* define a minimum required format for loklak data, so that they can be used by common services like maps. All data have to follow this format but can have custom fields as well.

To break a minimum amount of existing things another (more flexible) search endpoint should be implemented. The current `search.json` is always dedicated for twitter-like data. What do you think about this, and could this change break existing system ?

**Comment by Orbiter** [comment]
We are not building a general-purpose search engine. Everything we import must fit into the text + users + hashtags schema. Doing a general-purpose all-json search engine might be interesting, but out of focus. Furthermore I don't see currently a probem with the task since non-message like objects can just be referenced or attached as 'rich-content' object.

**Comment by zyzo** [comment]
This proposal was off the wrong track. Seems like `rich-content` object make things lot easier by allowing easy extension fields. Is searching on this object the same principle as native message fieds ?
