### ISSUE TITLE
Provide a json for the trending (hashtags) that are present as trends

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_server#63]
Similar to how twitter has trends that it shows up, if the loklak server can serve the trends it'd be great, we can have 2 steps to implement
- [ ] Global trends, bring the list of trends from twitter which are trending globally
- [ ] Regional trends, trends from twitter based on region / country
- [ ] A mix of both

https://github.com/loklak/loklak_webclient/issues/262 Is the dependant issue for solving this.

**Comment by Orbiter** [comment]
loklak_server can compute their own trends using the local index and aggregations. They can be retrieved i.e. using a time frame with
http://loklak.org/api/search.json?q=since:2015-07-04%20until:2015-07-06&source=cache&count=0&fields=hashtags&limit=6
I would suggest to use such self-generated data in favor of 'just a copy' of twitter trends.
