### ISSUE TITLE
Add more tests and continuous integration

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#736]
There are number of automated test that can be integrated with loklak. Which ones are suitable for the technologies used in the project? 

A list is here https://github.com/integrations

Please propose and integrate more tests e.g.
* [ ] https://www.codacy.com
* [ ] Cirlce CI
* [ ] Code Climate
* [ ] https://codecov.io
* [ ] https://coveralls.io
* [ ] https://gemnasium.com

**Comment by shivenmian** [comment]
@Orbiter disabled codacy. We don't need code quality tests atm I believe.

I think the tests are outdated though. @Orbiter I think the test folder hasn't been updated for a long time.

**Comment by mariobehling** [comment]
@shivenmian We need more tests and everyone should make tests as part of their PRs. Enable codacy and add other tests, please.

**Comment by mariobehling** [comment]
@Orbiter Codacy and other test CIs could give out "wrong error" messages. This is often the case, if different code conventions are followed. What conventions need to be followed?

**Comment by shivenmian** [comment]
@Orbiter do you believe the ```test``` directory needs updating? It hasn't been updated for a long while imo. Once that is set up well, we can enable codecov as well.

And do you believe codacy is needed? Because @sudheesh001 had enabled codacy at one point but you asked us to disabled it.

**Comment by DengYiping** [comment]
@mariobehling @Orbiter 

Besides this, I believe that loklak should be refactored in order to do unit test and integration test. 

Looking into the code, most of the java code in loklak uses `class Foo` instead of 'interface Foo'. This issue prohibits us to mock a object, say, for example, data access object. We are not able to change its implementation and mock a test dao object for other service. 

If we uses more interfaces, it will allow us to plug-in different implementation, the readability of code will be boosted, and the code will be more maintainable.

Plus, interfaces allow us to collaborate better. If there is a new need, we just write a new interface and let our community to finish the underlying implementation.

If you guys think it is a good idea to start refactoring the code, I will open a new issue and discuss about details.
