### ISSUE TITLE
Include rules for Date-Time in SUSI 

### ISSUE THREAD

**Issue by jig08** [loklak/loklak_server#738]
Using the console service implemented in PR https://github.com/loklak/loklak_server/pull/719, expand the ability of SUSI.

**Comment by daminisatya** [comment]
@jig08 Will this date-time service give answers for questions like

- Difference between timezones?

- What is the current time now?

- Timezone of a particular place?

- Date of a particular place? 

- Time of a particular place?

Im curious on what kinda rules this service can provide?

**Comment by jig08** [comment]
@daminisatya Currently, it aims to answer queries like:
* What is the time ?
* What is the date today ?
* Which day of the week is it ?
* What timezone are we in ?
etc.

For questions like:
>Difference between timezones?
What is the current time now?
Timezone of a particular place?
Date of a particular place?
Time of a particular place?

I would have to make use of a third party service like [www.timeanddate.com](http://www.timeanddate.com/) or any other

**Comment by sudheesh001** [comment]
> What is the time ?
What is the date today ?
Which day of the week is it ?
What timezone are we in ? etc.

For these questions we can directly query from the client itself in susi rather than request and load the server, the aim here should be to scrape timeanddate.com and display the contents after the required computation for the query given. Please refer https://github.com/loklak/loklak_server/pull/745#issuecomment-234462082

**Comment by sudheesh001** [comment]
Moving to #748
