### ISSUE TITLE
Profanity filter for search results

### ISSUE THREAD

**Issue by aneeshd16** [loklak/loklak_server#80]
This corresponds to the profanity filter mentioned here:
![image](https://cloud.githubusercontent.com/assets/5436027/8797822/95d32f40-2fbb-11e5-8832-7ef452b8832e.png)

It can be of the form `-/profanity`

**Comment by sudheesh001** [comment]
https://github.com/loklak/loklak_server/issues/25 Similar

**Comment by Orbiter** [comment]
just reopened that issue. Please expect a `-/profanity` constraint. That should be the syntax to be used here.

**Comment by mariobehling** [comment]
The filter would probably include filtering tweets with certain words as well as images.

**Comment by aneeshd16** [comment]
I don't think filtering images is possible as of now.

**Comment by Orbiter** [comment]
this is very true. We could try to identify such images using the text context of the tweet.

**Comment by mariobehling** [comment]
Lots of tweets have naked bodies that does not become apparent from the tweet text. @Orbiter how are other services doing this possibly? The profanity filter does not seem to make sense without including images.

**Comment by Orbiter** [comment]
we simply have two challenges: profanity detection for text and profanity detection for images. Lets solve this separately. While for the first case a solution is at hand, the second can be handled partly with a heuristic (detect by surrounding text) which leaves the remaining sub-problem 'image without text'. We can apply further heuristics like: if the image refers to a source which has already a profanity filter, it's accepted. Otherwise not.

**Comment by Orbiter** [comment]
implemented in https://github.com/loklak/loklak_server/commit/1f1bb73d8f9150336409834f99ccffad87cbfcec

just add `-/profanity` to search requests to filter out profanity content
