### ISSUE TITLE
Block retweets in search results

### ISSUE THREAD

**Issue by aneeshd16** [loklak/loklak_server#81]
This corresponds to the block retweets filter mentioned here:
![image](https://cloud.githubusercontent.com/assets/5436027/8797822/95d32f40-2fbb-11e5-8832-7ef452b8832e.png)

It can be of the form `-/retweets`

**Comment by Orbiter** [comment]
Right now I cannot see any retweet in our database, because they are not returned as search result in the twitter search result page which we scrape.
Retweets are only visible in twitter for two cases:
- if the user looks at his personal timeline (we don't have this because we don't evaluate twitters timline)
- if a search was made with `include:retweets` modifier (which we never used before).

Therefore, at this time, we don't have any retweets in our database.

**Comment by Orbiter** [comment]
according to https://github.com/loklak/loklak_server/issues/100 all tweets do not contain any retweets by default. To comply with the twitter-style of search operands, a new filter will not be `-/retweets` but `include:retweets`. This implies the following rule for your implementation in the wall:
- if 'Hide retweets' is set to NO: add the term `include:retweets` to the search term
- if 'Hide retweets' is set to YES: do not modify the search term, retweets are excluded by default.

**Comment by mariobehling** [comment]
@Orbiter This would still be a nice option to have, but I am not sure how much effort this entails and what priority this should have. Also this issue has been open for a year soon. So, what is the relevance with the current direction?

**Comment by mariobehling** [comment]
Closing this issue as this is not a focus atm. Please reopen, when it becomes relevant again.
