### ISSUE TITLE
Account.json can only be access from "localhost" and only from localhost

### ISSUE THREAD

**Issue by fuksi** [loklak/loklak_server#89]
This wasn't an issue for development, but for deployment it is. 
When development, the web client is localhost, so the request is allowed.

When deployed on a server, the web client is not anymore localhost but e.g. 
![image](https://cloud.githubusercontent.com/assets/6878677/8956611/5992fa56-3600-11e5-9a82-efc06d559c2e.png)

I suggest that there is an option in account servlet, that takes/adds CORS config from `customized_config`, so that it also allow request from the application main url

**Comment by sudheesh001** [comment]
Similar problem will occur while generating the map tile and markdown image generations. The localhost is no more localhost once deployed.
>I suggest that there is an option in account servlet, that takes/adds CORS config from customized_config, so that it also allow request from the application main url

I like the suggestion. Can this be implemented Michael ?

**Comment by Orbiter** [comment]
A flexible CORS configuration for this access method may be useful in large-scale distributed production environments where client and server are actually not on the same host. But in this case the problem is not located there. If client and server are on the same host, then this must be identifiable and therefore I do not want to follow the suggestion to make a CORS configuration here.

Focus: identify that client and server are on the same host:

The error message may be misleading: the server does not actually check that the access is from a host named 'localhost', instead it checks the client IP against all IPs that the local host of the server might have. I fixed this some weeks ago and believed that this is working right. This should also work if you submit a curl with the host name identical to the configured host name of the local host.

I re-tested this on loklak.org:
```
curl http://loklak.org/api/account.json?screen_name=loklak_app
```
works perfectly.

Please re-test again, submit the curl command from the same host where the server is running on. I don't believe this is a bug.

**Comment by fuksi** [comment]
At my server at domain: gofullstack.me, 
```bash
root@static:/var/www/html# curl http://gofullstack.me:9000/api/account.json?screen_name=loklak_app           
<html>                                                                                                       
<head>                                                                                                       
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>                                         
<title>Error 503 access only allowed from localhost</title>                                                  
</head>                                                                                                      
<body><h2>HTTP ERROR 503</h2>                                                                                
<p>Problem accessing /api/account.json. Reason:                                                              
<pre>    access only allowed from localhost</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>      
                                                                                                             
</body>                                                                                                      
</html>
```
