### ISSUE TITLE
Ensure html site renders Markdown correctly

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#898]
Looking through the html documentation site, e.g. http://loklak.github.io/loklak_server/docs/parsers.html, shows that some Markdown is not rendered correctly, e.g. compare here https://github.com/loklak/loklak_server/blob/development/docs/parsers.md

Please help to solve this issue.

@adarsh-ideal Would you be interested to look into this?

**Comment by fatimarafiqui** [comment]
The html link you gave i.e http://loklak.github.io/loklak_server/docs/parsers.html is not working.

**Comment by adarsh-ideal** [comment]
@mariobehling We are making another documentation site for loklak server which can be auto updated on each commit to the development branch and Abhishek is making use of Travis to get it done.
We talked and he will do it, I am learning all the functionalities of Travis right now.

You can close this issue because this file doesn't exist anymore.

**Comment by mariobehling** [comment]
@fatimarafiqui @adarsh-ideal Currently Javadocs are rendered in the gh-pages branch on each commit. They overwrote the previous page. I am not seeing how this is done though.

**Comment by mariobehling** [comment]
Ok, I found it the javadocs are generated through a script. I filed a follow up issue here: https://github.com/loklak/loklak_server/issues/921

**Comment by mariobehling** [comment]
Closing this issue in favor of https://github.com/loklak/loklak_server/issues/964
