### ISSUE TITLE
Auto-Generate HTML site on each commit from md files in development branch

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#900]
We have got a basic html site that uses md files in the gh-pages branch here http://loklak.github.io/loklak_server/

Please automatically render this page using the md files from the development branch on each commit. You might use travis to trigger this.

Ensure all links work in the rendered site.

**Comment by adarsh-ideal** [comment]
@mariobehling To autogenerate this site from development branch we need to create the site in development branch instead of gh-pages branch ( but github pages supports for master branch, gh-pages branch and master/docs folder to generate sites ). Current site will be updated with each commit on gh-pages branch.

If you want we can, create a documentation site on master branch, but it will be updated with each new commit on master branch not in development branch.

I don't know if we can generate a github pages site from development branch. See this image for information on locations which can be used to generate a github pages site.
![Uploading Screenshot from 2016-12-23 19-32-17.png…]()

**Comment by mariobehling** [comment]
Please use travis and an automatic site generator to build the site.

**Comment by niccokunzmann** [comment]
There is also the possibility to use readthedocs: It can build for every branch, usually the docs folder.
It uses Sphinx which has an easy-setup script. Also, it allows linking to code snippets. Many sites use readthedocs. Maybe that is something to look into.

**Comment by adarsh-ideal** [comment]
@mariobehling I'm working on it, will let you know after completing it.

**Comment by adarsh-ideal** [comment]
@mariobehling  @niccokunzmann Created the site and it also rebuilds after each commit. Also it uses development branch. Check the site: http://loklak-server.readthedocs.io/
It shows all md files, which are inside docs/ folder. But unfortunately, it doesn't show README.md because its in the root folder. We need to put the README.md file inside docs/ folder to show it. Java Docs will be also added at the same time. Everything else is perfect and updation of site is also automatically triggered by commits.

**Comment by mariobehling** [comment]
Thank you. Looks good. 

How could we adopt Read The docs to a more custom design?

Where are the javadocs?

**Comment by yukiisbored** [comment]
@mariobehling I think it's better to seperate the docs into it's own GitHub repo and we can use `sphinx` to generate the documentation page.

**Comment by mariobehling** [comment]
@yukiisbored There are many ways that can work somehow. Keeping the documentation with the project is standard in many projects and anyone forking the repo would have everything at hand. We are already following the way to make use of different branches in this project and other FOSSASIA projects, e.g. in Open Event. So, this could be regarded as our best practices.

**Comment by Abhi2424shek** [comment]
Can we have the Travis solution then @mariobehling @adarsh-ideal

**Comment by mariobehling** [comment]
Sure, travis sounds good.

**Comment by Abhi2424shek** [comment]
@mariobehling I would do that pls wait...

**Comment by mariobehling** [comment]
@Abhi2424shek How is it going?

**Comment by Abhi2424shek** [comment]
@mariobehling just a sec would push a PR today itself...

**Comment by mariobehling** [comment]
Closing this issue in favor of https://github.com/loklak/loklak_server/issues/964
