### ISSUE TITLE
Invalid Link

### ISSUE THREAD

**Issue by Marauderer97** [loklak/loklak_server#915]
Clicking on Home,API,Architecture,Tutorials,Apps,Downloads in the nav-bar in loklak.org redirects to an invalid link, and gives the following error
![image](https://cloud.githubusercontent.com/assets/20185076/21519949/cae59f5c-cd16-11e6-9623-bd464a69827b.png)

**Comment by Marauderer97** [comment]
I see that this issue has already been reported and corrected in #906 , but only the Blog link works now, the rest still direct me to invalid pages.

**Comment by yukiisbored** [comment]
@Marauderer97 The Navbar items are defined by `/cms/topmenu.json` HTTP GET, which is handled by `org.loklak.api.cms.TopMenuService`. 

I think the problem is caused by `loklak.js`, because If you see the generated navbar items the `href` have an extra `/` at the beginning, this caused the browser to think the content is on the same host.

I'm actually have no idea which line on `loklak.js` causes it (I'm not that good with JQuery), the links on `TopMenuService` are ok.
