### ISSUE TITLE
How can Kubernetes help us scaling loklak and running it more reliably? What is the best approach?

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#946]
We are using Kubernetes in the eventyay project. How could it help us scaling loklak and running it more reliably? What is the best approach?

**Comment by sudheesh001** [comment]
Will have a look into this. Added to my todo list.

**Comment by sudheesh001** [comment]
With some research done, I can say that this will definitely work, since we package fat-jar's in the ant jar build process, we can run the jars on the kubernetes cluster. I've started experimenting with an openshift instance which uses kubernetes to do this. Will report back.

**Comment by yukiisbored** [comment]
@sudheesh001 We currently do not have a way to generate a "fat jar". I don't know how you can do it correctly with Ant because some of the libraries have "services" which should be handled carefully. I know how you can do it with Gradle by using [the shadow plugin](https://github.com/johnrengelman/shadow).

**Comment by sudheesh001** [comment]
@yukiisbored Would you like to give the shadow plugin a try, it's new for me and I would love to see how it works.

**Comment by yukiisbored** [comment]
@sudheesh001 Sure, I'll create a PR.

**Comment by yukiisbored** [comment]
@sudheesh001 https://github.com/loklak/loklak_server/pull/1006

**Comment by mariobehling** [comment]
Thanks!
