### ISSUE TITLE
Find a way to get more than 20 tweets with TwitterScraper

### ISSUE THREAD

**Issue by yukiisbored** [loklak/loklak_server#961]
Currently, TwitterScraper can only search up to 20 tweets via Twitter's Search page. This is due to the fact Twitter only gives 20 and you can only get more if you run the Javascript code (which we can't).

**Comment by smokingwheels** [comment]
Try a few Frontends 5 or More and adjust DOS settings accordingly on your Backend and see what happens. 
Count the number of lines in you Dump file when on a Hot Topic. Also you can watch Twitter to see the number over the harvest period to reference from.

**Comment by singhpratyush** [comment]
If you take a look at `XHR` requests made while scrolling down at twitter search page, a pattern can be seen. We may directly make these `XHR` calls and get more tweets from there.

[Here](https://github.com/Jefferson-Henrique/GetOldTweets-python/blob/master/got3/manager/TweetManager.py#L5) is an implementation in Python.

[Here](https://twitter.com/i/search/timeline?vertical=default&q=fossasia&include_available_features=1&include_entities=1&max_position=TWEET-848865504668274698-853175154897178624-BD1UO2FFu9QAAAAAAAAETAAAAAcAAAASAAAgASAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAIAAAAAAAAAgQAAAAAABACAAAAAAAAAAAAggAAAAIAAAAAAACCAAAAAAAAAQAAAAAAABAAAAAAIAAAAAAAAgAAAAgAAAAAAAAAABAAAACAAIAAAAAAAAAAAIAQgAAAAAAAAACAAAAAAEEAAAAAAAAAAAAAAAA&reset_error_state=false) is an example of content that we'll need to parse in order to get Tweets.

**Comment by mariobehling** [comment]
@singhpratyush It would be great, if you could implement this. Code would be awesome.

**Comment by singhpratyush** [comment]
@mariobehling: Will work on it. Please assign the issue.

**Comment by singhpratyush** [comment]
@mariobehling @yukiisbored:  How shall the upper limit on the number of Tweets for a search query be decided?

**Comment by vibhcool** [comment]
@singhpratyush loklak can get upto 100 tweets in range 1 to 100, but can't exceed the number 100. 
example:- loklak.org/api/search.json?q=singapore&maximumRecords=100

**Comment by singhpratyush** [comment]
@vibhcool: It's about how many Tweets can be collected for a given search query using the harvester.

**Comment by singhpratyush** [comment]
@yukiisbored @Orbiter @daminisatya: I've implemented it in [this](https://github.com/singhpratyush/loklak_server/tree/more-tweets-961) branch. I think that there is an issue.

What happens now is that `TwitterScraper` replicates the way in which lazy loading of Twitter search page works. This involves making multiple requests to attain a minimum number of tweets (specified [here](https://github.com/singhpratyush/loklak_server/blob/more-tweets-961/src/org/loklak/harvester/TwitterScraper.java#L62)).

What I think is happening is that most of the queries are terminated if not completed quickly. I observed this by looking at the logs which specified that for some queries, few Tweets were collected but the collection process never completed.

Do I need to take care of something which I am missing?

**Comment by yukiisbored** [comment]
Actually, I should've closed this issue because `KaizenHarverster` can be configured to get more than 20 tweets. But, nice try though. What we can do is to add `<existing query> since:<oldest tweet date>` to the queue after we're done with the query and it has >=20 tweets.

**Comment by singhpratyush** [comment]
In that case, shall I make it as a function that would just keep on fetching Tweets until there are no more results for the query?

**Comment by yukiisbored** [comment]
@singhpratyush Make it a part of https://github.com/loklak/loklak_server/blob/development/src/org/loklak/harvester/strategy/KaizenHarvester.java#L81.
